name: Deploy to trigger

on:
    push:
        branches:
            - main
        paths:
            - 'packages/trigger/**'

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup Node 22
              uses: actions/setup-node@v4
              with:
                  node-version: 22
                  registry-url: https://registry.npmjs.org/

            - name: Setup PNPM
              uses: pnpm/action-setup@v4.0.0
              with:
                  version: 9.12.2

            - name: Install
              run: pnpm install --frozen-lockfile

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Login to Docker
              uses: docker/login-action@v3
              with:
                  registry: trigger-registry.willow.rest
                  username: trigger
                  password: ${{ secrets.TRIGGER_DOCKER_REGISTRY_PASSWORD }}

            - name: Deploy Trigger.dev
              env:
                  TRIGGER_ACCESS_TOKEN: ${{ secrets.TRIGGER_ACCESS_TOKEN }}
                  TRIGGER_API_URL: https://trigger.willow.sh
              run: pnpm --filter trigger-tasks exec trigger deploy --self-hosted --push
